steps:
  - name: "gcr.io/google.com/cloudsdktool/cloud-sdk"
    entrypoint: "bash"
    args:
      - "-c"
      - |
        gsutil ls gs://fresh1 --impersonate-service-account=189614076516-compute@developer.gserviceaccount.com


options:
  logging: CLOUD_LOGGING_ONLY
timeout: 1200s

